---
name: Check for lint/build errors

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Use the Node.js version that matches your project requirements

      - name: Install Yarn
        run: yarn install

  lint:
    name: Lint Code Base, Spelling, Link Check
    needs: setup
    runs-on: ubuntu-latest
    permissions:
        contents: read
        steps:
            - uses: actions/checkout@v3
            
            - name: Lint
            uses: Consensys/docs-gha/lint@main
            with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
  linkCheck:
    name: Link Checking
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@v3
      - name: LinkCheck
        uses: Consensys/docs-gha/linkcheck@main
        with:
          FILE_EXTENSION: "${{ matrix.file-extensions }}"
